networks:
  default:
    name: strongswan
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-strongswan
    # enable_ipv6: true
    ipam:
      config:
        - subnet: 10.0.1.0/24
        # - subnet: fd00:1::/64

services:
  strongswan:
    image: moonpath/strongswan:latest
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE=alpine:latest
      tags:
        - "moonpath/strongswan:latest"
    container_name: strongswan
    hostname: strongswan
    restart: unless-stopped
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv4.ip_forward: "1"
      net.ipv6.conf.all.forwarding: "1"
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      DOMAIN: ${DOMAIN:-$HOSTNAME}
      USERNAME: ${USERNAME:-username}
      PASSWORD: ${PASSWORD:-password}
    deploy:
      resources:
        limits:
          memory: 0.5g
